name: Github actions events

on:
 workflow_dispatch: 
 push:
 pull_request: 
 schedule:
   - cron: "*/5 * * * *"


jobs:
  event-job-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger event
        run: echo "My trigger is ${{ github.event_name }}"      

      - name: Print branch 
        run: echo "My branch is ${{ github.ref_name}}"
      - name: Print event
        run: echo "My branch is ${{ github.action }}"      
      - name: My branch name
        run: echo "My branch principal is ${{ github.ref }}"
      - name: If with main branch
        run: echo "My branch principal is called master? ${{ github.ref == 'refs/heads/master'}}"
      - name: variables environment
        run: echo "name=cristian" >> "$GITHUB_ENV"  
      - name: variables environment
        run: echo "environment=dev" >> "$GITHUB_ENV"  
      - name: variables environment
        run: echo "$GITHUB_ENV"  

            