name: Understand runners

on:
 workflow_dispatch:
 push: 
    branches: 
      - master
jobs:
    runners-info:
        runs-on: ubuntu-latest
        steps:
            - name: Print runners details
              run: |
                echo "Runner name: ${{ runner.name}}"
                echo "Runner OS: ${e{ runner.os}}"
                echo "Runner Architecture: ${{ runner.arch}}"
                echo "Runner workspace: ${{ runner.workspace}}"
                echo "Runner Architecture: $RUNNER_ARCH"                                