name: github-init
on: push

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Init S.O
              run: cat /etc/os-release

            - name: User S.O
              run: whoami ; id
            
            - name: Validate files
              run: touch file{1..20}.txt
            
            - name: List files
              run: ls -l 